version: '3'
services:
  python3:
    restart: always
    build: 
      dockerfile: ./docker/Dockerfile.local
    container_name: 'python3'
    tty: true
    volumes:
      - ./app:/root/app
    ports:
      - "8080:5000"

